services:
  base:
    build:
      context: .
      target: base
      args:
        ROS_DISTRO: humble
    container_name: aloha4franka_container

    # === Tune this to your application ===
    network_mode: "host"
    ipc: "host"
    pid: "host"
    privileged: true
    # ===

    command: /bin/bash
    tty: true
    stdin_open: true

    volumes:
      - $HOME/.Xauthority:/root/.Xauthority 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw 
      - /dev:/dev

    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      ROS_DOMAIN_ID: 100
      RCUTILS_COLORIZED_OUTPUT: 1
      SHELL: /bin/bash
      DEVICE: /dev/gripper_right
      NAMESPACE: right
      ROS_NETWORK_INTERFACE: lo
      RMW: fast

    cap_add:
      - SYS_NICE

    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856

  overlay:
    extends: base
    image: aloha4franka:overlay
    build:
      context: .
      target: overlay
    container_name: aloha4franka_overlay_container

  launch_aloha_gripper:
    extends: overlay
    container_name: aloha4franka_gripper_cyclone_container
    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
      source install/setup.bash &&
      export ROS_NETWORK_INTERFACE=${ROS_NETWORK_INTERFACE:-lo} &&
      RMW=${RMW:-} source src/crisp_controllers_demos/scripts/setup_middleware.sh &&
      ros2 launch aloha4franka_bringup aloha_gripper.launch.py namespace:=${NAMESPACE} device:=${DEVICE}"
