site_name: aloha4franka
nav:
  - Home: index.md
  - Shopping List: shopping_list.md
  - Assembly Guide: assembly_guide.md
  - Getting Started: getting_started.md


repo_url: https://github.com/tum-lsy/aloha4franka

theme:
  name: material
  # logo: images/logo.png
  # favicon: images/favicon.png
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: teal
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    # text: Poppins
    # text: Montserrat
    # text: Tahoma
    # text: Roboto
    code: Source Code Pro
  features:
    - header.autohide
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    # - navigation.sections
    # - navigation.expand


  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  # - mkdoxy:
  #     projects:
  #       crisp_controllers: # name of project must be alphanumeric + numbers (without spaces)
  #         src-dirs: .
  #         full-doc: True # if you want to generate full documentation
  #         doxy-cfg: # standard doxygen configuration (key: value)
  #           FILE_PATTERNS: "*.cpp *.h*" # specify file patterns to filter out
  #           RECURSIVE: True # recursive search in source directorie


extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/utiasDSL/crisp_controllers

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true 
      clickable_checkbox: true

extra_css:
  - stylesheets/extra.css
