/**:
  controller_manager:
    ros__parameters:
      update_rate: 50  # Hz

      gripper_position_controller:
        type: position_controllers/JointGroupPositionController

      gripper_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      trigger_position_controller:
        type: position_controllers/JointGroupPositionController

      trigger_effort_controller:
        type: effort_controllers/JointGroupEffortController
        
      trigger_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
        
      joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController

  gripper_position_controller:
    ros__parameters:
      joints:
        - left_finger_joint


  trigger_effort_controller:
    ros__parameters:
      joints:
        - trigger_joint

  trigger_position_controller:
    ros__parameters:
      joints:
        - trigger_joint

  gripper_state_broadcaster:
    ros__parameters:
      use_local_topics: true
      joints: ["left_finger_joint"]

  trigger_state_broadcaster:
    ros__parameters:
      use_local_topics: true
      joints: ["trigger_joint"]

  joint_trajectory_controller:
    ros__parameters:
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7

      command_interfaces:
        - position

      state_interfaces:
        - position
        - velocity

