controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    position_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


position_controller:
  ros__parameters:
    joints:
      - left_finger_joint

    command_interfaces:
      - position

    state_interfaces:
      - position

joint_state_broadcaster:
  ros__parameters:
    joints:
      - left_finger_joint
